# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../configs/ingress-nginx

namespace: ingress-nginx


patches:
- path: output-json-patch.yml
  target:
    group: logging.banzaicloud.io
    kind: Output
    name: ingress-nginx
    namespace: ingress-nginx
    version: v1beta1
- path: output.yml
