# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - datasource
  - deploy.yaml
  - service-monitor.yaml
  - dashboards

images:
  - name: docker.io/grafana/loki
    newName: registry.sighup.io/fury/grafana/loki
    newTag: 3.5.3
  - name: docker.io/nginxinc/nginx-unprivileged
    newName: registry.sighup.io/fury/nginxinc/nginx-unprivileged
    newTag: 1.29-alpine

secretGenerator:
  - name: loki
    files:
      - configs/config.yaml
  - name: minio-credentials-loki
    envs:
      - minio-credentials.env
