apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-distributed-ingester
  namespace: logging
spec:
  template:
    spec:
      containers:
      - name: ingester
        args:
          - -config.file=/etc/loki/config/config.yaml
          - -ingester.flush-on-shutdown=true
          - -log.level=debug
          - -target=ingester